### ISSUE TITLE
THIS IS 🔥

### ISSUE THREAD

**Issue by todrobbins** [amiaopensource/open-workflows#1] opened 2016-11-03 02:17 UTC
MOAR OF THIS
PR COMING YOUR WAY

**Comment by ablwr** [comment] 2016-11-03 03:01
YEEEEHAW!!! Added you to the team too!

**Comment by dericed** [comment] 2016-11-03 14:21
I appreciate that there's an open issue for how great this repository is.

**Comment by ablwr** [comment] 2016-11-03 18:13
Secondary issue: Where are @todrobbins's contributions??

**Comment by retokromer** [comment] 2016-11-03 18:23
🔥🔥🔥

**Comment by ablwr** [comment] 2016-11-15 00:53
WHERE'S THE FIRE TOD!!!!!

**Comment by kieranjol** [comment] 2016-11-15 16:05
lol

**Comment by todrobbins** [comment] 2016-12-15 05:31
Wow. I don't know how I missed the notification a month ago, but I feel sufficiently shamed to make a difference.

**Comment by ablwr** [comment] 2016-12-15 15:36
👼

**Comment by ablwr** [comment] 2017-01-24 20:06
@todrobbins

**Comment by ablwr** [comment] 2017-01-24 20:06
:)

**Comment by todrobbins** [comment] 2017-01-27 15:38
At least ONE link coming today!

**Comment by ablwr** [comment] 2017-03-03 19:31
@todrobbins should I close this issue???

**Comment by kieranjol** [comment] 2017-03-03 20:00
I love this issue so much 🔥

**Comment by todrobbins** [comment] 2017-03-06 22:47
TOO MUCH PRESSURE

**Comment by todrobbins** [comment] 2017-03-06 22:47
😉

**Comment by dericed** [comment] 2017-03-07 00:24
Perhaps a regression, but I'm reopening this issue, because THIS IS STILL 🔥

**Comment by todrobbins** [comment] 2017-04-21 21:01
hey, check out #22

**Comment by ablwr** [comment] 2017-04-21 21:17
YEAHH!!!!!!

**Comment by kieranjol** [comment] 2017-04-21 21:17
:fire: :fire:

**Closed as completed** 2017-04-21 21:18 UTC
Labels: enhancement
